name: PHPUnit
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: 'ubuntu-latest'
    container: 'byjg/php:${{ matrix.php-version }}-cli'
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.0"
          - "7.4"
          - "7.3"
          - "7.2"

    steps:
      - uses: actions/checkout@v3
      - run: composer install
      - name: Run command line migrations
        run: |
          set -e

          export MIGRATE_CONNECTION=sqlite:///tmp/teste.db
          export MIGRATE_PATH=example/sqlite/

          scripts/migrate reset --yes -vvv
          scripts/migrate version
          scripts/migrate update -vvv --up-to=1
          scripts/migrate version
          scripts/migrate up -vvv
          scripts/migrate version
          scripts/migrate down -vvv --up-to=0
          scripts/migrate version
          scripts/migrate update -vvv --up-to=1
          scripts/migrate version

  Documentation:
    runs-on: 'ubuntu-latest'
    needs: Build
    if: github.ref == 'refs/heads/master'
    env:
      DOC_GITHUB_TOKEN: '${{ secrets.DOC_TOKEN }}'
    steps:
      - uses: actions/checkout@v3
      - run: curl https://opensource.byjg.com/add-doc.sh | bash /dev/stdin php migration-cli