name: PHPUnit
on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: 'ubuntu-latest'
    container: 'byjg/php:${{ matrix.php-version }}-cli'
    strategy:
      matrix:
        php-version:
          - "8.3"
          - "8.2"
          - "8.1"

    steps:
      - uses: actions/checkout@v4
      - run: composer install
      - run: composer vendor/bin/psalm
      - name: Run command line migrations
        run: |
          set -e

          export MIGRATE_CONNECTION=sqlite:///tmp/teste.db
          export MIGRATE_PATH=example/sqlite/

          scripts/migrate reset --yes -vvv
          scripts/migrate version
          scripts/migrate update -vvv --up-to=1
          scripts/migrate version
          scripts/migrate up -vvv
          scripts/migrate version
          scripts/migrate down -vvv --up-to=0
          scripts/migrate version
          scripts/migrate update -vvv --up-to=1
          scripts/migrate version

  Documentation:
    if: github.ref == 'refs/heads/master'
    needs: Build
    uses: byjg/byjg.github.io/.github/workflows/add-doc.yaml@master
    with:
      folder: php
      project: ${{ github.event.repository.name }}
    secrets: inherit

